spring:
  datasource:
    url: jdbc:h2:mem:numterpark
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
  devtools:
    livereload:
      enabled: true
logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.orm: TRACE
#    org.springframework.transaction: TRACE
#    com.zaxxer.hikari: TRACE
#    com.mysql.cj.jdbc: TRACE
